name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: false

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure identity + LFS
        run: |
          git config user.name "GitHub→GitLab Mirror Bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git lfs install --skip-smudge
          git config --global lfs.locksverify false

      - name: Build remote and verify access
        env:
          GL_TOKEN: ${{ secrets.GITLAB_REMOTE }}   # token glpat-...
          GL_PATH:  ${{ vars.GITLAB_PATH }}        # ex.: meu-grupo/sub/meu-repo
        run: |
          set -e
          [ -n "$GL_PATH" ] || { echo "Defina a variable GITLAB_PATH"; exit 1; }
          REMOTE="https://oauth2:${GL_TOKEN}@gitlab.com/${GL_PATH}.git"
          REMOTE="${REMOTE%/}"
          git ls-remote "$REMOTE" >/dev/null
          git remote add gitlab "$REMOTE" || git remote set-url gitlab "$REMOTE"
          git remote -v

      - name: Sync branches and tags (skip main on GitLab)
        run: |
          set -e
          # Puxa todas as branches/tags do GitHub (origin) para refs remotas locais
          git fetch --prune --tags origin '+refs/heads/*:refs/remotes/origin/*'

          # Lista de branches no origin
          mapfile -t ORIGIN_BRANCHES < <(git for-each-ref --format='%(refname:strip=3)' refs/remotes/origin)

          # 1) Push (force-safe) de TODAS as branches, EXCETO main
          for br in "${ORIGIN_BRANCHES[@]}"; do
            if [ "$br" = "main" ]; then
              echo "Pulando push da branch protegida 'main'"
              continue
            fi
            git push gitlab +refs/remotes/origin/$br:refs/heads/$br
          done

          # 2) Prune seguro: apaga no GitLab branches que não existem mais no origin (exceto main)
          mapfile -t GL_BRANCHES < <(git ls-remote --heads gitlab | awk '{print $2}' | sed 's#refs/heads/##')
          for br in "${GL_BRANCHES[@]}"; do
            if [ "$br" = "main" ]; then continue; fi
            if ! printf '%s\n' "${ORIGIN_BRANCHES[@]}" | grep -qx "$br"; then
              echo "Removendo no GitLab: $br (não existe no origin)"
              git push gitlab :refs/heads/$br
            fi
          done

          # 3) Tags (com prune)
          git push --prune gitlab +refs/tags/*:refs/tags/*

          # 4) LFS (se houver)
          git lfs push --all gitlab || true


