name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:
  # (Opcional) sincronismo periódico de segurança
  schedule:
    - cron: "*/30 * * * *"  # a cada 30 minutos

concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: false

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure identity + LFS
        run: |
          git config user.name "GitHub→GitLab Mirror Bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git lfs install --skip-smudge

      - name: Push --mirror to GitLab
        env:
          GITLAB_REMOTE: ${{ secrets.GITLAB_REMOTE }}
        run: |
          git remote add gitlab "$GITLAB_REMOTE"
          # Envia tudo (branches, tags, deleções)
          git push --mirror gitlab
          # Se tiver LFS, envia também
          git lfs push --all gitlab || true

  # (Opcional) job de "pull do GitLab" como fallback nas execuções agendadas
  pull_from_gitlab_fallback:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync from GitLab (fetch → push origin)
        env:
          GITLAB_REMOTE: ${{ secrets.GITLAB_REMOTE }}
        run: |
          git remote add gitlab "$GITLAB_REMOTE" || true
          git fetch --prune --tags gitlab
          git push --mirror origin
