name: Mirror to GitLab

on:
  push:
    branches: ["**"]
    tags: ["**"]
  delete:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: false

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure identity + LFS
        run: |
          git config user.name "GitHub→GitLab Mirror Bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git lfs install --skip-smudge

      - name: Build remote and verify access
        env:
          GL_TOKEN: ${{ secrets.GITLAB_REMOTE }}   # <= só o token glpat-...
          GL_PATH:  ${{ vars.GITLAB_PATH }}        # <= ex.: meu-grupo/subgrupo/meu-repo
        run: |
          set -e
          if [ -z "$GL_PATH" ]; then
            echo "Defina a Repository variable GITLAB_PATH (ex.: meu-grupo/subgrupo/meu-repo)"; exit 1
          fi
          REMOTE="https://oauth2:${GL_TOKEN}@gitlab.com/${GL_PATH}.git"
          REMOTE="${REMOTE%/}"                       # remove / final se houver
          echo "Testando acesso ao remoto: $REMOTE"
          git ls-remote "$REMOTE" >/dev/null
          git remote add gitlab "$REMOTE" || git remote set-url gitlab "$REMOTE"
          git remote -v

      - name: Push --mirror to GitLab
        run: |
          git push --mirror gitlab
          git lfs push --all gitlab || true
